fix(guidelines): remove consumer-facing guidelines already available as portal content
otto-de/api-guidelines pull request #43
Opened 2023-06-21 05:56 UTC by BirgitBader

Fixes https://github.com/otto-ec/ottoapi_portal/issues/1950

Changelog:

### Remove

The following rules have been removed as this is consumer-facing content and already available in the REST API sections "Getting started" and "About the API".
- MUST use Proof Key for Code Exchange (PKCE) for mobile and JavaScript apps
- MUST NOT use Implicit Grant flow
- MUST use Bearer Authentication
- MUST set user agent request header
- SHOULD use Accept and Content-Type headers with profile parameter

2023-06-21 09:35 UTC, maxedenharter0507 requested changes

2023-06-21 09:35 UTC, maxedenharter0507 commented on api-guidelines/rest/authorization/oauth/rules/must-use-bearer-authentication.md
That rule could also be interpreted as provider-facing rule because the provider needs to validate the token and therefore it must be delivered by a defined protocol. We also have a new linter rule for specs regarding that rule. See https://github.com/otto-de/api-guidelines/blob/main/src/linting/rules/use-bearer-authentication.ts

2023-06-21 09:53 UTC, maxedenharter0507 approved these changes

2023-06-23 11:32 UTC, cgebken commented
@BirgitBader FYI: I removed the rule you have readded after Max' comment from the changelog entry before approving this PR.

2023-06-23 11:32 UTC, cgebken approved these changes

2023-06-23 11:34 UTC, merged