chore(guidelines): Relate to rfc9457 instead of rfc7807
otto-de/api-guidelines pull request #80
Opened 2024-10-29 13:20 UTC by stefanschmidt1701

### Update

- Refactored rule [R000034].
- Refactored rule [R000037].
- Refactored rule [R000040].

2024-10-30 08:25 UTC, maxedenharter0507 requested changes
Thanks for your contribution :-)

2024-10-30 08:25 UTC, maxedenharter0507 commented on api-guidelines/rest/errors/error-handling/rules/must-use-problem-json-as-error-response-format.md
> +The [`type`](https://www.rfc-editor.org/rfc/rfc9457#section-3.1) of the problem object should be used to identify the problem type globally.
```suggestion
The [`type`](https://www.rfc-editor.org/rfc/rfc9457#section-3.1.1) of the problem object should be used to identify the problem type globally.
```

2024-11-14 07:39 UTC, maxedenharter0507 approved these changes

2025-02-11 14:26 UTC, kiriakos approved these changes

2025-02-11 14:27 UTC, kiriakos commented
@cgebken LGTM, its in your hands now

2025-02-12 11:03 UTC, merged